// <auto-generated />
using System;
using CineDoors.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CineDoors.Infrastructure.Migrations
{
    [DbContext(typeof(CineDoorsDbContext))]
    partial class CineDoorsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CineDoors.Core.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateOnly?>("LastReleaseCheck")
                        .HasColumnType("date")
                        .HasColumnName("last_release_check");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_app_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_app_user_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_app_user_username");

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("CineDoors.Core.Entities.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("AirDate")
                        .HasColumnType("date")
                        .HasColumnName("air_date");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("runtime_minutes");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("season_id");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_episode");

                    b.HasIndex("AirDate")
                        .HasDatabaseName("ix_episode_air_date");

                    b.HasIndex("SeasonId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_episode_season_id_number");

                    b.ToTable("episode", (string)null);
                });

            modelBuilder.Entity("CineDoors.Core.Entities.EpisodeWatch", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("EpisodeId")
                        .HasColumnType("integer")
                        .HasColumnName("episode_id");

                    b.Property<DateTime>("WatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("watched_at");

                    b.HasKey("UserId", "EpisodeId")
                        .HasName("pk_episode_watch");

                    b.HasIndex("EpisodeId")
                        .HasDatabaseName("ix_episode_watch_episode_id");

                    b.ToTable("episode_watch", (string)null);
                });

            modelBuilder.Entity("CineDoors.Core.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackdropPath")
                        .HasColumnType("text")
                        .HasColumnName("backdrop_path");

                    b.Property<string>("Genres")
                        .HasColumnType("text")
                        .HasColumnName("genres");

                    b.Property<string>("Overview")
                        .HasColumnType("text")
                        .HasColumnName("overview");

                    b.Property<string>("PosterPath")
                        .HasColumnType("text")
                        .HasColumnName("poster_path");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("runtime_minutes");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<int>("TmdbId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_id");

                    b.HasKey("Id")
                        .HasName("pk_movie");

                    b.HasIndex("TmdbId")
                        .IsUnique()
                        .HasDatabaseName("ix_movie_tmdb_id");

                    b.ToTable("movie", (string)null);
                });

            modelBuilder.Entity("CineDoors.Core.Entities.MovieTracking", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer")
                        .HasColumnName("movie_id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<bool>("Notify")
                        .HasColumnType("boolean")
                        .HasColumnName("notify");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("WatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("watched_at");

                    b.HasKey("UserId", "MovieId")
                        .HasName("pk_movie_tracking");

                    b.HasIndex("MovieId")
                        .HasDatabaseName("ix_movie_tracking_movie_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_movie_tracking_user_id_status");

                    b.ToTable("movie_tracking", (string)null);
                });

            modelBuilder.Entity("CineDoors.Core.Entities.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<int>("SeriesId")
                        .HasColumnType("integer")
                        .HasColumnName("series_id");

                    b.HasKey("Id")
                        .HasName("pk_season");

                    b.HasIndex("SeriesId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_season_series_id_number");

                    b.ToTable("season", (string)null);
                });

            modelBuilder.Entity("CineDoors.Core.Entities.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackdropPath")
                        .HasColumnType("text")
                        .HasColumnName("backdrop_path");

                    b.Property<DateOnly?>("FirstAirDate")
                        .HasColumnType("date")
                        .HasColumnName("first_air_date");

                    b.Property<string>("Genres")
                        .HasColumnType("text")
                        .HasColumnName("genres");

                    b.Property<string>("Overview")
                        .HasColumnType("text")
                        .HasColumnName("overview");

                    b.Property<string>("PosterPath")
                        .HasColumnType("text")
                        .HasColumnName("poster_path");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<int>("TmdbId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_id");

                    b.HasKey("Id")
                        .HasName("pk_series");

                    b.HasIndex("TmdbId")
                        .IsUnique()
                        .HasDatabaseName("ix_series_tmdb_id");

                    b.ToTable("series", (string)null);
                });

            modelBuilder.Entity("CineDoors.Core.Entities.SeriesTracking", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("SeriesId")
                        .HasColumnType("integer")
                        .HasColumnName("series_id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<bool>("Notify")
                        .HasColumnType("boolean")
                        .HasColumnName("notify");

                    b.HasKey("UserId", "SeriesId")
                        .HasName("pk_series_tracking");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("ix_series_tracking_series_id");

                    b.ToTable("series_tracking", (string)null);
                });

            modelBuilder.Entity("CineDoors.Core.Entities.Episode", b =>
                {
                    b.HasOne("CineDoors.Core.Entities.Season", null)
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_episode_season_season_id");
                });

            modelBuilder.Entity("CineDoors.Core.Entities.EpisodeWatch", b =>
                {
                    b.HasOne("CineDoors.Core.Entities.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_episode_watch_episode_episode_id");

                    b.HasOne("CineDoors.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_episode_watch_app_user_user_id");
                });

            modelBuilder.Entity("CineDoors.Core.Entities.MovieTracking", b =>
                {
                    b.HasOne("CineDoors.Core.Entities.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_tracking_movie_movie_id");

                    b.HasOne("CineDoors.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_tracking_app_user_user_id");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CineDoors.Core.Entities.Season", b =>
                {
                    b.HasOne("CineDoors.Core.Entities.Series", null)
                        .WithMany("Seasons")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_season_series_series_id");
                });

            modelBuilder.Entity("CineDoors.Core.Entities.SeriesTracking", b =>
                {
                    b.HasOne("CineDoors.Core.Entities.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_series_tracking_series_series_id");

                    b.HasOne("CineDoors.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_series_tracking_app_user_user_id");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("CineDoors.Core.Entities.Season", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("CineDoors.Core.Entities.Series", b =>
                {
                    b.Navigation("Seasons");
                });
#pragma warning restore 612, 618
        }
    }
}
